//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Indicadores.Models.BaseDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_Indicadores : DbContext
    {
        public BD_Indicadores()
            : base("name=BD_Indicadores")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Catalogo> TB_Catalogo { get; set; }
        public virtual DbSet<TB_Estado> TB_Estado { get; set; }
        public virtual DbSet<TB_Indicador> TB_Indicador { get; set; }
        public virtual DbSet<TB_IndicadorPosvalor> TB_IndicadorPosvalor { get; set; }
        public virtual DbSet<TB_Metadata> TB_Metadata { get; set; }
        public virtual DbSet<TB_Periodo> TB_Periodo { get; set; }
        public virtual DbSet<TB_Posvalor> TB_Posvalor { get; set; }
        public virtual DbSet<TB_UnidadMedida> TB_UnidadMedida { get; set; }
        public virtual DbSet<V_SelectIndicadores> V_SelectIndicadores { get; set; }
        public virtual DbSet<V_SelectMetadata> V_SelectMetadata { get; set; }
    }
}
