//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Indicadores.Models.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_IndicadorPosvalor
    {
        public int IdIndiPos { get; set; }
        public int IdIndicador { get; set; }
        public int IdPosvalor { get; set; }
        public int Orden { get; set; }
    
        public virtual TB_Indicador TB_Indicador { get; set; }
        public virtual TB_Posvalor TB_Posvalor { get; set; }
    }
}
