//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Indicadores.Models.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Indicador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Indicador()
        {
            this.TB_IndicadorPosvalor = new HashSet<TB_IndicadorPosvalor>();
        }
    
        public int IdIndicador { get; set; }
        public int IdCatalogo { get; set; }
        public int IdUnidad { get; set; }
        public int IdPeriodo { get; set; }
        public int IdEstado { get; set; }
    
        public virtual TB_Catalogo TB_Catalogo { get; set; }
        public virtual TB_Estado TB_Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_IndicadorPosvalor> TB_IndicadorPosvalor { get; set; }
        public virtual TB_Periodo TB_Periodo { get; set; }
        public virtual TB_UnidadMedida TB_UnidadMedida { get; set; }
    }
}
