//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Indicadores.Models.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SelectMetadata
    {
        public int Indicador { get; set; }
        public string Metadata { get; set; }
        public string Posvalor { get; set; }
    }
}
